### ISSUE TITLE
AI server crashing after recompiling DNA files

### ISSUE THREAD

**Issue by alexanderr** [loblao/libpandadna#15]
```
TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
DCFile::read of astron/dclass/otp.dc
DCFile::read of astron/dclass/toon.dc
:AstronInternalRepository: Now connecting to 127.0.0.1:7100...
:AstronInternalRepository: Connecting to gameserver directly (no proxy).
:AstronInternalRepository: Connecting to //127.0.0.1:7100 via HTTP interface.
:AstronInternalRepository: Successfully connected to //127.0.0.1:7100.
:AstronInternalRepository: Connected successfully.
:AstronInternalRepository: Creating ToontownDistrictAI(401000001)...
:AstronInternalRepository: Claiming ownership of channel ID: 401000001...
:AstronInternalRepository: Created ToontownDistrictStats(401000002)
:AstronInternalRepository: Creating managers...
:AstronInternalRepository: Creating safe zones...
:HoodAI: Creating objects... Toontown Central
:HoodAI: Creating objects... Toontown Central, Silly Street
Assertion failed: _current_index + sizeof(tempvar) <= _datagram->get_length() at
 line 203 of c:\users\toontowninfinite\desktop\github\panda3d\panda\src\express\
datagramIterator.I
Traceback (most recent call last):
  File "C:\Panda3D-1.9.0\direct\extensions_native\HTTPChannel_extensions.py", li
ne 36, in doTask
    task.callback(*task.callbackArgs)
  File "C:\Panda3D-1.9.0\direct\distributed\ConnectionRepository.py", line 563,
in httpConnectCallback
    successCallback(*successArgs)
  File "C:\Panda3D-1.9.0\direct\distributed\AstronInternalRepository.py", line 4
77, in __connected
    self.handleConnected()
  File "toontown\ai\ToontownAIRepository.py", line 191, in handleConnected
    self.createSafeZones()
  File "toontown\ai\ToontownAIRepository.py", line 138, in createSafeZones
    self.hoods.append(TTHoodAI.TTHoodAI(self))
  File "toontown\hood\TTHoodAI.py", line 17, in __init__
    ToontownGlobals.ToontownCentral)
  File "toontown\hood\HoodAI.py", line 35, in __init__
    dnaData = simbase.air.loadDNAFileAI(dnaStore, dnaFileName)
  File "toontown\ai\ToontownAIRepository.py", line 218, in loadDNAFileAI
    return loadDNAFileAI(dnastore, filename)
  File "toontown\dna\DNAParser.py", line 50, in loadDNAFileAI
    data = dnaLoader.loadDNAFileAI(dnaStorage, file)
  File "toontown\dna\DNALoader.py", line 268, in loadDNAFileAI
    self.__loadDNAFileBase(store, str(file))
  File "toontown\dna\DNALoader.py", line 253, in __loadDNAFileBase
    self.handleStorageData(dgi)
  File "toontown\dna\DNALoader.py", line 141, in handleStorageData
    endPoint = dgi.getUint16()
```

**Comment by CrankySupertoon** [comment]
@chandler14362 can you reupload that zip file
