### ISSUE TITLE
__main__.DNAError: no such font: mickey

### ISSUE THREAD

**Issue by gamesawdrew** [loblao/libpandadna#19]
C:\libpandadna-master\compiler>python compile.py toontown_central_sz.dna toontow
n_central_sz.pdna
DirectStart: Starting the game.
:audio(error):   load_dso(libp3openal_audio.so) failed, will use NullAudioManage
r
:audio(error):     Not a valid Win32 application
Reading DNA file... toontown_central_sz.dna
Traceback (most recent call last):
  File "compile.py", line 148, in <module>
    process_single_file(file)
  File "compile.py", line 99, in process_single_file
    rootData = loadDNAFile(dnaStore, filename)
  File "compile.py", line 72, in loadDNAFile
    return str(root.traverse(recursive=True, verbose=args.verbose))
  File "C:\libpandadna-master\compiler\dna\components\DNAGroup.py", line 53, in
traverse
    packer += self.traverseChildren(verbose=verbose)
  File "C:\libpandadna-master\compiler\dna\components\DNAGroup.py", line 59, in
traverseChildren
    packer += child.traverse(recursive=True, verbose=verbose)
  File "C:\libpandadna-master\compiler\dna\components\DNAGroup.py", line 53, in
traverse
    packer += self.traverseChildren(verbose=verbose)
  File "C:\libpandadna-master\compiler\dna\components\DNAGroup.py", line 59, in
traverseChildren
    packer += child.traverse(recursive=True, verbose=verbose)
  File "C:\libpandadna-master\compiler\dna\components\DNAVisGroup.py", line 50,
in traverse
    packer += self.traverseChildren(verbose=verbose)
  File "C:\libpandadna-master\compiler\dna\components\DNAGroup.py", line 59, in
traverseChildren
    packer += child.traverse(recursive=True, verbose=verbose)
  File "C:\libpandadna-master\compiler\dna\components\DNAGroup.py", line 53, in
traverse
    packer += self.traverseChildren(verbose=verbose)
  File "C:\libpandadna-master\compiler\dna\components\DNAGroup.py", line 59, in
traverseChildren
    packer += child.traverse(recursive=True, verbose=verbose)
  File "C:\libpandadna-master\compiler\dna\components\DNAProp.py", line 28, in t
raverse
    packer += self.traverseChildren(verbose=verbose)
  File "C:\libpandadna-master\compiler\dna\components\DNAGroup.py", line 59, in
traverseChildren
    packer += child.traverse(recursive=True, verbose=verbose)
  File "C:\libpandadna-master\compiler\dna\components\DNASign.py", line 28, in t
raverse
    packer += self.traverseChildren(verbose=verbose)
  File "C:\libpandadna-master\compiler\dna\components\DNAGroup.py", line 59, in
traverseChildren
    packer += child.traverse(recursive=True, verbose=verbose)
  File "C:\libpandadna-master\compiler\dna\components\DNASignBaseline.py", line
84, in traverse
    font = globalStorage.getFont(self.code)
  File "C:\libpandadna-master\compiler\dna\base\DNAStorage.py", line 33, in getF
ont
    raise DNAError('no such font: %s' % code)
__main__.DNAError: no such font: mickey

C:\libpandadna-master\compiler>pause
Press any key to continue . . .

**Comment by gamesawdrew** [comment]
Please Help!

**Comment by loblao** [comment]
You are using compiler utility incorrectly. I'm working on moving signs back to C++ reader in the next couple of days, which will make compiling DNAs quite easy.

**Comment by gamesawdrew** [comment]
Ok. Also i have a question about animated props for Toontown.
on streets i get this in my console: :TrashcanInteractiveProp(warning): calcHoodId couldn't parse hidden/dna/root/toontownCentral/2339/interactive_prop_phase_5_models_char__ttc_trashcan_DNARoot using 0

**Comment by gamesawdrew** [comment]
I recompiled the TTC Dna in the TTI src, whenever i go into a TTC zone (street or playground) i crash and get this error:
http://pastebin.com/uS7yBeUy

**Comment by gamesawdrew** [comment]
Hey, do you mind helping me get TTI Src to use the C++ reader?
Thanks
