### ISSUE TITLE
Bug when Compiling PDNA files on Windows 10 build 10586.63

### ISSUE THREAD

**Issue by Spiderlover** [loblao/libpandadna#46]
This is the error I get when compiling .pdna files on Windows 10 build 10586.63 

Traceback (most recent call last):
  File "compile.py", line 106, in <module>
    process_single_file(file)
  File "compile.py", line 67, in process_single_file
    rootData = loadDNAFile(dnaStore, filename)
  File "compile.py", line 61, in loadDNAFile
    root.read(f)
  File "C:\Users\Josh\Documents\libpanda\libpandadna-master\compiler\dna\components\DNARoot.py", line 20, in read
    parser.parse(stream.read())
  File "C:\Users\Josh\Documents\libpanda\libpandadna-master\compiler\ply\yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "C:\Users\Josh\Documents\libpanda\libpandadna-master\compiler\ply\yacc.py", line 1181, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "C:\Users\Josh\Documents\libpanda\libpandadna-master\compiler\ply\yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "C:\Users\Josh\Documents\libpanda\libpandadna-master\compiler\dna\parser\parser.py", line 1031, in p_error
    raise DNAError('Syntax error at line %s token=%s' % sub)
__main__.DNAError: Syntax error at line 1400 token=LexToken(UNQUOTED_STRING,'PDNA',1400,0)

**Comment by loblao** [comment]
Can you pastebin your file?

**Comment by Spiderlover** [comment]
sure

**Comment by Spiderlover** [comment]
http://pastebin.com/NgwSrmGF

**Comment by loblao** [comment]
Can you pastebin your **DNA file**?

**Comment by Spiderlover** [comment]
sure :)

http://pastebin.com/XxJ2cXZE

**Comment by loblao** [comment]
Unable to reproduce. This file compiles correctly here. Make sure you encode it as "UTF-8 without BOM"

Notepad++:
![notepad++](https://cloud.githubusercontent.com/assets/6625888/12512648/b1a98daa-c100-11e5-8535-c5368c0d7200.png)

**Comment by Spiderlover** [comment]
ok, thanks for the help :)
