### ISSUE TITLE
undefined symbol on Ubuntu 14.04

### ISSUE THREAD

**Issue by K1999** [loblao/libpandadna#47]
```
TTLocalizer: Running in language: English
OTPLocalizer: Running in language: English
:AstronInternalRepository: Using connect method 'http'
DCFile::read of dependencies/astron/dclass/toontown.dc
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/git/server/toontown/uberdog/ServiceStart.py", line 55, in <module>
    config.GetInt('air-stateserver', 4002))
  File "toontown/uberdog/ToontownUberRepository.py", line 15, in __init__
    ToontownInternalRepository.__init__(self, baseChannel, serverId, dcSuffix='UD')
  File "toontown/distributed/ToontownInternalRepository.py", line 17, in __init__
    dcSuffix=dcSuffix, connectMethod=connectMethod, threadedNet=threadedNet)
  File "/usr/share/panda3d/direct/distributed/AstronInternalRepository.py", line 139, in __init__
    self.readDCFile(dcFileNames)
  File "/usr/share/panda3d/direct/distributed/ConnectionRepository.py", line 311, in readDCFile
    self.importModule(dcImports, moduleName, importSymbols)
  File "/usr/share/panda3d/direct/distributed/ConnectionRepository.py", line 408, in importModule
    module = __import__(moduleName, globals(), locals(), importSymbols)
  File "toontown/suit/DistributedSuitPlannerAI.py", line 6, in <module>
    import DistributedSuitAI
  File "toontown/suit/DistributedSuitAI.py", line 7, in <module>
    import SuitPlannerBase
  File "toontown/suit/SuitPlannerBase.py", line 6, in <module>
    from toontown.dna.DNAParser import *
  File "toontown/dna/DNAParser.py", line 3, in <module>
    from libpandadna import *
ImportError: ./libpandadna.so: undefined symbol: _ZN14PointerToArrayIhEaSEOS0_
Warning: pandac.PandaModules is deprecated, import from panda3d.core instead
```

I don't know whats going on to be honest with you. I had an issue earlier where it said `libstdc++.so.6: version GLIBCXX_3.4.20 not found`. Fixed that but now i can't even get it to load past that.

**Comment by loblao** [comment]
Reproduced.

**Comment by decryptable** [comment]
I'm also getting this issue

**Comment by Skilledfire** [comment]
Able to reproduce on Elementary OS Loki (0.4.1). Seems to happen at least on Debian-based distros, if not other versions as well.

**Comment by loblao** [comment]
This error exists when there's a mismatch between the Panda3D libs you linked libpandadna.so against and the libs you're loading.
